[package]
name = "phonic"
version = "0.0.1"
edition = "2021"

[workspace]
resolver = "2"
members = [
	"crates/phonic_core",
	"crates/phonic_signal",
	"crates/phonic_io",
	"crates/phonic_io_core",
	"crates/phonic_format_wave",
	"crates/phonic_codec_pcm",
	"crates/phonic_cpal",
	"crates/phonic_rtrb",
	"examples/player",
	"examples/export",
	"examples/converter",
]

[features]
default = ["signal"]
signal = ["dep:phonic_signal"]

# io
io = ["dep:phonic_io"]
io-full = ["io", "wave", "pcm"]
wave = ["io", "phonic_io/wave"]
pcm = ["io", "phonic_io/pcm"]

# integrations
cpal = ["dep:phonic_cpal"]
rtrb = ["dep:phonic_rtrb"]

[dependencies]
phonic_core = { version = "0.1.0", path = "crates/phonic_core" }
phonic_signal = { version = "0.1.0", path = "crates/phonic_signal", optional = true }
phonic_io = { version = "0.1.0", path = "crates/phonic_io", optional = true }
phonic_cpal = { version = "0.1.0", path = "crates/phonic_cpal", optional = true }
phonic_rtrb = { version = "0.1.0", path = "crates/phonic_rtrb", optional = true }

[workspace.dependencies]
log = "0.4"
