[workspace]
resolver = "2"
members = [
	"crates/syphon",
	"crates/syphon_core",
	"crates/syphon_dsp",
	"crates/syphon_io",
	"crates/syphon_io_cpal",
	"crates/syphon_signal",
	"examples/player",
	"examples/synth",
]
