[workspace]
resolver = "2"
members = [
	"crates/syphon",
	"crates/syphon_core",
	"crates/syphon_signal",
	"crates/syphon_synth",
	"crates/syphon_io",
	"crates/syphon_io_core",
	"crates/syphon_format_wave",
	"crates/syphon_codec_pcm",
	"crates/syphon_cpal",
	"examples/player",
	"examples/synth",
	"examples/converter",
]
