[package]
name = "phonic_synth"
version = "0.1.0"
edition = "2021"

[dependencies]
phonic_core = { version = "0.1.0", path = "../phonic_core" }
phonic_signal = { version = "0.1.0", path = "../phonic_signal" }
