[package]
name = "syphon_cpal"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.2"
syphon_core = { version = "0.1.0", path = "../syphon_core" }
syphon_signal = { version = "0.1.0", path = "../syphon_signal" }
