[package]
name = "syphon_signal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syphon_core = { version = "0.1.0", path = "../syphon_core" }
