[package]
name = "phonic_buf"
version = "0.1.0"
edition = "2021"

[dependencies]
phonic_signal = { version = "0.1.0", path = "../phonic_signal", optional = true }

[features]
default = ["signal"]
signal = ["dep:phonic_signal"]
