[package]
name = "phonic_io"
version = "0.0.1"
edition = "2021"

[features]
dyn-io = []

all-formats = ["wave"]
wave = []

all-codecs = ["pcm"]
pcm = []

[dependencies]
phonic_macro = { version = "0.0.1", path = "../phonic_macro" }
phonic_signal = { version = "0.0.1", path = "../phonic_signal" }
